title: "Fundación Multiactiva TransformArte"
description: "Transformando vidas a través del arte y la educación"
baseurl: ""
url: ""

contact:
  phone: "305 431 4805"
  email: "fumtransformarte@gmail.com"
  address: "Carrera 12 A # 77A - 113, Piso 1"
  whatsapp: "573054314805"
  whatsapp_url: "https://wa.me/573054314805"

social:
  instagram: "https://www.instagram.com/fundatransformarte"
  linkedin: "https://www.linkedin.com/in/fundación-multiactiva-transformarte-636a35355/"
  youtube: "https://www.youtube.com/@FundaciónMultiactivaTransforma"

volunteer_form: "https://docs.google.com/forms/d/e/1FAIpQLSfRKbkx5uIie2RNg1IJGofXKaMPK9xBwIRMn2N5HiMuF8BPaA/viewform?usp=header"

donations_online_url: "https://vaki.co/es/vaki/pequenos-y-grandes-artistas?utm_source=copy&utm_medium=vaki-page&utm_campaign=v4"
donations_materials_form: "https://docs.google.com/forms/d/e/1FAIpQLScSiL2yJ-pwE7YeRzKovK56lELxtJr1R_2zKzA7rPTtYBgOMw/viewform?usp=header"

navigation:
  - title: "Inicio"
    url: "/"
  - title: "Quiénes Somos"
    url: "/quienes-somos"
  - title: "Voluntariado"
    url: "/voluntariado"
  - title: "Aliados"
    url: "/aliados"
  - title: "Informes"
    url: "/informe-gestion"
  - title: "Contáctanos"
    url: "/#contact"

markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: assets/css
  style: compressed
